JAVAC = javac
JAVAC_FLAGS = -sourcepath .

JAVA = java
JAVA_FLAGS =

CUP = java_cup.Main
CUPFLAGS = -nopositions -expect 100

JLEX = JLex.Main

LATEX = latex
DVIPS = dvips

all: test Parser.ps

test: absyn Parser/Yylex.class Parser/PrettyPrinter.class Parser/Test.class Parser/ComposVisitor.class Parser/AbstractVisitor.class Parser/FoldVisitor.class Parser/AllVisitor.class Parser/parser.class Parser/sym.class Parser/Test.class

.PHONY: absyn

%.class: %.java
	${JAVAC} ${JAVAC_FLAGS} $^

absyn: Parser/Absyn/Exp.java Parser/Absyn/EAdd.java Parser/Absyn/ESub.java Parser/Absyn/EMul.java Parser/Absyn/EDiv.java Parser/Absyn/EPar_Esq.java Parser/Absyn/EPar_Dir.java Parser/Absyn/EInt.java
	${JAVAC} ${JAVAC_FLAGS} $^

Parser/Yylex.java: Parser/Yylex
	${JAVA} ${JAVA_FLAGS} ${JLEX} Parser/Yylex

Parser/sym.java Parser/parser.java: Parser/Parser.cup
	${JAVA} ${JAVA_FLAGS} ${CUP} ${CUPFLAGS} Parser/Parser.cup
	mv sym.java parser.java Parser/

Parser/Yylex.class: Parser/Yylex.java Parser/sym.java

Parser/sym.class: Parser/sym.java

Parser/parser.class: Parser/parser.java Parser/sym.java

Parser/PrettyPrinter.class: Parser/PrettyPrinter.java

Parser.dvi: Parser.tex
	${LATEX} Parser.tex

Parser.ps: Parser.dvi
	${DVIPS} Parser.dvi -o Parser.ps

clean:
	 rm -f Parser/Absyn/*.class Parser/*.class
	 rm -f .dvi Parser.aux Parser.log Parser.ps  *.class

distclean: vclean

vclean:
	 rm -f Parser/Absyn/Exp.java Parser/Absyn/EAdd.java Parser/Absyn/ESub.java Parser/Absyn/EMul.java Parser/Absyn/EDiv.java Parser/Absyn/EPar_Esq.java Parser/Absyn/EPar_Dir.java Parser/Absyn/EInt.java Parser/Absyn/Exp.class Parser/Absyn/EAdd.class Parser/Absyn/ESub.class Parser/Absyn/EMul.class Parser/Absyn/EDiv.class Parser/Absyn/EPar_Esq.class Parser/Absyn/EPar_Dir.class Parser/Absyn/EInt.class
	 rm -f Parser/Absyn/*.class
	 rmdir Parser/Absyn/
	 rm -f Parser.tex Parser.dvi Parser.aux Parser.log Parser.ps 
	 rm -f Parser/Yylex Parser/Parser.cup Parser/Yylex.java Parser/VisitSkel.java Parser/ComposVisitor.java Parser/AbstractVisitor.java Parser/FoldVisitor.java Parser/AllVisitor.java Parser/PrettyPrinter.java Parser/Skeleton.java Parser/Test.java Parser/sym.java Parser/parser.java Parser/*.class
	 rm -f Makefile
	 rmdir -p Parser/

